import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
const records = [
  { cca3: "ISL", slug: "iceland", name: "Iceland", officialName: "Iceland", capital: "Reykjavik", region: "Europe", subregion: "Northern Europe", continent: "Europe", flag: "https://flagcdn.com/w640/is.png", flagAlt: "The flag of Iceland", population: 376248, area: 103000, languages: ["Icelandic"], currencies: ["Icelandic króna"], timezones: ["UTC"], summary: "A volcanic island of glaciers, geothermal springs, and long summer days." },
  { cca3: "JPN", slug: "japan", name: "Japan", officialName: "Japan", capital: "Tokyo", region: "Asia", subregion: "Eastern Asia", continent: "Asia", flag: "https://flagcdn.com/w640/jp.png", flagAlt: "The flag of Japan", population: 125124989, area: 377930, languages: ["Japanese"], currencies: ["Japanese yen"], timezones: ["UTC+09:00"], summary: "An island nation where ancient traditions and restless innovation sit side by side." },
  { cca3: "KEN", slug: "kenya", name: "Kenya", officialName: "The Republic of Kenya", capital: "Nairobi", region: "Africa", subregion: "Eastern Africa", continent: "Africa", flag: "https://flagcdn.com/w640/ke.png", flagAlt: "The flag of Kenya", population: 53771300, area: 580367, languages: ["English", "Swahili"], currencies: ["Kenyan shilling"], timezones: ["UTC+03:00"], summary: "From highland forests to the Indian Ocean, Kenya is a place of extraordinary ecological range." },
  { cca3: "PRT", slug: "portugal", name: "Portugal", officialName: "The Portuguese Republic", capital: "Lisbon", region: "Europe", subregion: "Southern Europe", continent: "Europe", flag: "https://flagcdn.com/w640/pt.png", flagAlt: "The flag of Portugal", population: 10305564, area: 92090, languages: ["Portuguese"], currencies: ["Euro"], timezones: ["UTC"], summary: "A sunlit Atlantic country shaped by sea journeys, tiled streets, and a lyrical food culture." }
];
async function main() { for (const record of records) await prisma.country.upsert({ where: { cca3: record.cca3 }, create: record, update: record }); console.log(`Seeded ${records.length} starter countries.`); }
main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
